apiVersion: v1
kind: PersistentVolume
metadata:
  name: gluster-pv-1
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  glusterfs:
    endpoints: glusterfs-cluster
    path: gvol0
  persistentVolumeReclaimPolicy: Recycle
